// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1nVvsdpUOqksOLhIl1xLzzj06mRnGSHU',
    appId: '1:386247410897:web:48275be023a6188ae971f0',
    messagingSenderId: '386247410897',
    projectId: 'rit-app-25',
    authDomain: 'rit-app-25.firebaseapp.com',
    storageBucket: 'rit-app-25.firebasestorage.app',
    measurementId: 'G-4GC0GC4H4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsmtggP36pDujB8mWTE0mZ9edf-tI-d6A',
    appId: '1:386247410897:android:e9c2970fd7043981e971f0',
    messagingSenderId: '386247410897',
    projectId: 'rit-app-25',
    storageBucket: 'rit-app-25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr5wOLfY5xHU2CjeZEVhn3UYAxi6PsADY',
    appId: '1:386247410897:ios:2ba2d04979a2fcf4e971f0',
    messagingSenderId: '386247410897',
    projectId: 'rit-app-25',
    storageBucket: 'rit-app-25.firebasestorage.app',
    iosBundleId: 'com.example.civilProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr5wOLfY5xHU2CjeZEVhn3UYAxi6PsADY',
    appId: '1:386247410897:ios:2ba2d04979a2fcf4e971f0',
    messagingSenderId: '386247410897',
    projectId: 'rit-app-25',
    storageBucket: 'rit-app-25.firebasestorage.app',
    iosBundleId: 'com.example.civilProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1nVvsdpUOqksOLhIl1xLzzj06mRnGSHU',
    appId: '1:386247410897:web:72c0f0455f12f154e971f0',
    messagingSenderId: '386247410897',
    projectId: 'rit-app-25',
    authDomain: 'rit-app-25.firebaseapp.com',
    storageBucket: 'rit-app-25.firebasestorage.app',
    measurementId: 'G-MTV4WVBZNW',
  );
}
